<?php
require __DIR__.'/db.php';$pageTitle='Departments';$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{if(($_POST['action']??'')==='create'){ $st=$pdo->prepare('INSERT INTO departments(dept_code,dept_name,location) VALUES(?,?,?)');$st->execute([$_POST['dept_code'],$_POST['dept_name'],$_POST['location']]);$msg='Department created.';} elseif(($_POST['action']??'')==='delete'){ $st=$pdo->prepare('DELETE FROM departments WHERE dept_id=?');$st->execute([$_POST['dept_id']]);$msg='Department deleted.';}}catch(Throwable $e){$msg='Error: '.$e->getMessage();}}
$rows=$pdo->query('SELECT d.*,COUNT(s.student_id) student_count FROM departments d LEFT JOIN students s ON s.dept_id=d.dept_id GROUP BY d.dept_id ORDER BY d.dept_name')->fetchAll();
include __DIR__.'/partials/header.php';
?>
<div class="hero"><div><h1>Departments</h1><p>Master data table with one-to-many relationships.</p></div></div><?php if($msg): ?><div class="notice success"><?=htmlspecialchars($msg)?></div><?php endif; ?><div class="form-card"><form method="post"><input type="hidden" name="action" value="create"><div class="form-grid"><div class="field"><label>Code</label><input name="dept_code" required></div><div class="field"><label>Name</label><input name="dept_name" required></div><div class="field"><label>Location</label><input name="location" value="Nagpur"></div><div class="field"><button class="btn">Create Department</button></div></div></form></div>
<div class="table-wrap"><table class="table"><tr><th>ID</th><th>Code</th><th>Name</th><th>Location</th><th>Students</th><th>Action</th></tr><?php foreach($rows as $r): ?><tr><td><?=$r['dept_id']?></td><td><?=$r['dept_code']?></td><td><?=htmlspecialchars($r['dept_name'])?></td><td><?=htmlspecialchars($r['location'])?></td><td><?=$r['student_count']?></td><td><form method="post" onsubmit="return confirm('Delete department? It must not have students or courses.')"><input type="hidden" name="action" value="delete"><input type="hidden" name="dept_id" value="<?=$r['dept_id']?>"><button class="btn small danger">Delete</button></form></td></tr><?php endforeach; ?></table></div><?php include __DIR__.'/partials/footer.php'; ?>
